### ISSUE TITLE
垂直排版的文字旋转之后无法在CnOcr中进行识别

### ISSUE THREAD

**Issue by vinovo** [breezedeus/cnstd#13]
比如这个图片中的文字
![image](https://user-images.githubusercontent.com/35409183/90715731-ffd2d880-e25f-11ea-8c33-55a760dfa767.png)

CnStd返回的cropped image为

![image](https://user-images.githubusercontent.com/35409183/90715822-37da1b80-e260-11ea-8f1d-33365ec2b7ef.png)

返回的结果没法在CnOcr使用。
请问这个有什么比较好的解决方法吗，可否在返回的dict里面添加旋转相关的信息？

另外感谢作者付出的心血！

**Comment by breezedeus** [comment]
对，cnocr现在是不支持垂直的文字的。

**Comment by vinovo** [comment]
请问后续有计划添加相关支持吗？或者有没有什么好的现有的解决方法呢
