### ISSUE TITLE
预训练的下载链接失效

### ISSUE THREAD

**Issue by dygcjlu** [breezedeus/cnstd#20]
预训练的下载链接失效了，请问是否可以更新？

**Comment by maodijim** [comment]
默认的 mobilenetv3 下载链接好像是挂了百度网盘也打不开
但是resnet50_v1b 的下载链接还是好使的 
把model name改成resnet50_v1b 就能跑了
```
std = CnStd(model_name="resnet50_v1b")
```

**Comment by breezedeus** [comment]
更新到最新版，然后都有默认下载地址，应该可用
