### ISSUE TITLE
无法准确识别长图

### ISSUE THREAD

**Issue by yfq512** [breezedeus/cnstd#38]
### 正文部分的文本框的位置有误
![lala3](https://user-images.githubusercontent.com/52442277/158928742-6e63cea1-c0fd-42b2-8a20-aba0a4064099.jpg)

**Comment by breezedeus** [comment]
@yfq512 把图片长度的参数设大点试试
`        resized_shape: Tuple[int, int] = (768, 768),` 这个中的第一个值，比如2048，甚至更大

**Comment by yfq512** [comment]
@breezedeus 试过了，不起作用，我再试试别的开源吧
