### ISSUE TITLE
为什么多张图片纵向拼接后的文本检测和单张图片的文本检测差别很大

### ISSUE THREAD

**Issue by wengad82** [breezedeus/CnSTD#62]
我有一个PDF转成IMAGE的图片（总3页，转成了3张图片），转换后的3张image用cnstd来分别检测文本，结果可以检测出来所有文本。
但是把这3张images纵向拼接后，再用同样的程序进行进行检测文本，只检测出来可怜的一些文本。
这会不是什么原因？

**Comment by breezedeus** [comment]
因为做检测前会对图片做resize，你多图拼完后再resize完可能导致文字小到检测不出来。

**Comment by wengad82** [comment]
OK，多谢，我直接把resized_shape 调整成拼接后的尺寸大小，就可以了。
